
const CHANGE_SEQUENCE = "CHANGE_SEQUENCE";
const CHANGE_WINDOW_SIZE = "CHANGE_WINDOW_SIZE";
const CHANGE_SCORING_MATRIX = "CHANGE_SCORING_MATRIX";
const INSPECT_COORDINATE = "INSPECT_COORDINATE";
const KEYBOARD_DIRECTION = "KEYBOARD_DIRECTION";
const SLIDE_TWO_SEQS = "SLIDE_TWO_SEQS";
const CHANGE_GREY_SCALE = "CHANGE_GREY_SCALE"

export {
    CHANGE_SEQUENCE,
    CHANGE_WINDOW_SIZE,
    CHANGE_SCORING_MATRIX,
    INSPECT_COORDINATE,
    KEYBOARD_DIRECTION,
    SLIDE_TWO_SEQS,
    CHANGE_GREY_SCALE,
};
