
const CHANGE_SEQUENCE = "CHANGE_SEQUENCE";
const CHANGE_WINDOW_SIZE = "CHANGE_WINDOW_SIZE";
const CHANGE_SCORING_MATRIX = "CHANGE_SCORING_MATRIX";
const INSPECT_COORDINATE = "INSPECT_COORDINATE";
const CHANGE_GREY_SCALE = "CHANGE_GREY_SCALE"

export {
    CHANGE_SEQUENCE,
    CHANGE_WINDOW_SIZE,
    CHANGE_SCORING_MATRIX,
    INSPECT_COORDINATE,
    CHANGE_GREY_SCALE,
};
