import { SCORING_MATRIX_NAMES, DNA, PROTEIN } from '../constants/constants';


const smallExample = {
    s1: "ATGC",
    s2: "ATTAGGCGAGGAG",
    s1Type: DNA,
    s2Type: DNA,
    scoringMatrix: SCORING_MATRIX_NAMES.BLOSUM80,
    matrixSize: 13,
};

// s1: YWHAB from Uniprot, len 246
// s2: YWHAZ Coelacant ortholog
const orthologExample = {
    s1: "MTMDKSELVQKAKLAEQAERYDDMAAAMKAVTEQGHELSNEERNLLSVAYKNVVGARRSSWRVISSIEQKTERNEKKQQMGKEYREKIEAELQDICNDVLELLDKYLIPNATQPESKVFYLKMKGDYFRYLSEVASGDNKQTTVSNSQQAYQEAFEISKKEMQPTHPIRLGLALNFSVFYYEILNSPEKACSLAKTAFDEAIAELDTLNEESYKDSTLIMQLLRDNLTLWTSENQGDEGDAGEGEN",
    s2: "RKPLQTPTPIRRLWTMDTSELVQKAKLAEQAERYDDMAASMKAVTEQGAELSNEERNLLSVAYKNVVGARRSSWRVISSIEQKTEGSEQKQQMAREYREKIEAELRDICNDVLGLLDKYLIANASKAESKVFYLKMKGDYYRYLAEVAAGEDKKSTVDHSQQVYQEAFEISKKEMTSTHPIRLGLALNFSVFYYEILNLPEQACGLAKTAFDDAISELDKLGDESYKDSTLIMQLLRDNLTVST",
    s1Type: PROTEIN,
    s2Type: PROTEIN,
    scoringMatrix: SCORING_MATRIX_NAMES.BLOSUM80,
    matrixSize: 246,
};

let defaultState = {
    s1: '',
    s2: '',
    s1Type: PROTEIN,
    s2Type: PROTEIN,
    scores: [],
    windowSize: 5,
    scoringMatrix: SCORING_MATRIX_NAMES.IDENTITY,
    i: 0,
    j: 0,
    matrixSize: 0,
};

Object.assign(defaultState, orthologExample);


export default defaultState;
